#!/bin/sh
### BEGIN INIT INFO
# Provides:          domoticz2mongo
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Domoticz2Mongo
# Description:       Domoticz2Mongo
### END INIT INFO

case "$1" in
  start)
    /bin/su - pi -c "/apps/domoticz2mongo/start.sh"
    ;;
  stop)
    /bin/su - pi -c "/apps/domoticz2mongo/stop.sh"
    ;;
  *)
    echo "Usage: /etc/init.d/domoticz2mongo {start|stop}"
    exit 1
    ;;
esac

exit 0
